language: generic
cache:
  directories:
    - $PWD/data
matrix:
  include:
    - language: python
      os: osx
      before_install:
        - tools/build_concorde.sh
    - language: python
      os: linux
      before_install:
        - tools/build_concorde.sh

install:
  - tools/bootstrap_edm.sh
  - export PATH="$PATH:$HOME/bin"
  - edm run -e travisci -- python setup.py develop
script:
  - edm run -e travisci -- python -m unittest discover -v pytsp
